language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: QTw+AyygM/r9ebzjBzJAdVJCAR05UjXh6dE3GDAdxPCXnLpxvcaemuD8XyhlfnPlkOUwZ2yXgxnyxDoU8VI0AkoLvS5rexaJPyzovbfewNA/biNlgfzXz8BI93k5Q9satfvwi0QuAuz7WWJWFi7bbHOV0byAoTPw1vz3v497/53R0zeMmPnq6WWwrq0pQ8ELzfW+e4D/Q8XqGbcN0Yb5nHXpyXbi7k+dftyZDkRsagnPnjRglN7yAn2yJtrZTjVhAScTwTigQTs4kpe7OjKEsy5jbLK9ygXoZvifeaz5+Ct7gkX61aJ27RUYNs9nE8JArWGgiKt09LBG3bBKBgvF0XV+v9ng8rkHPNwofxcaehQ55TDHJv8oeLxR4CJ0qcyiVaomBz88jGrwrW5Y+g8m0yuxYUARk7ujal8gM6S6FRA/zemRjhI39nCJkcW5YcSG3aaPy39fmPtEII8qG+YXbvPycVvdAa3FvQFd1AaG4WflwK6YX0OfyidGkYQ8Q5yvVXpmhTiAMBuH9xwpOPOMyhTfxu91sVxhwvGP2iEICO9sw45WGpYqSqwyERPUNzxchUAoEIeXsuTisxeneScddfmr6TL8dJRCE9MjQDeY1b+X6R71y6mmO5jgROjTqAAGhmBx+sejgM4v20Ry5pCAsS38CdNOwZwLqvrFjcRDmks=
  app: radiant-dusk-68990
  on:
    repo: ASARIR/projet
