language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: Cbe4aQQYY23jnpqoU3VjI2EusJ9ws2clA21JtNm+1YDLptMAtWfczqw3rRVmhs2PBnLhocfMZ2vLE+qQBzMOb6HNEpBez9vQd/pJ412LQ3vMZkaG6yBymyPbGUbiSGFMH4zCU/ggsWbAIYDkgUl98ZxTBb+QcrUTs94y3BuHgWNXSXTOuq4eiSE4H9VUXO/577iSL6KH1MbnUM5xoYURXshjSOhY9TKj7P09qcvokKTKhs+icp3n68p67CNaLs4JtA7CUqg5fYtJg7IwrSzupbrkaI4pvxFiHcoiM0hR+aYH93EouixH8XoMII4o0O2otlBckew4FIp7fe3G4vSnuEXSFTbbtho5DF0IQYoCAe6aS+TzjJXGJ8L5CMqW94IEATv1HabklQw+FK2itOktb3mgmPay4VjxwW/c9vQOJDRws7npqXKB3ijiy9JUWM+NTv7/w5vI4DwxQckVWN/a+kg5lRKb0egWkTGc1GkqZltmJeLsY+D15IUpHdy4Y/mQ6i2vzhyvOpmn/KkGWw/0wENQEZWoiI8XJRiEsJ3BORsOKaNErGY2RTwLTHVlz9hLakwBbxStonWOtt5WzBjMop4n0gCYTVmoeQHB+HifGgglEwjjHYFF09Og4DRA+tyLStvz9RsX8pW3sqs+WN6lHhzQ4cFHk5WfBysSvhakvFU=
  app: radiant-dusk-68990
  on:
    repo: ASARIR/projet
