language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: nYOOfE7SUpft8dh8MzQUCM/yra/jcCkwa13vQjEgb+sH1r9bsHI2WhKB7+pZv+DAhxPYHWRq1b3usC01i8JCbRQHvGzLIDMVKuOh/xWAePzcPis4sQqEiA6PaxS817Ib2rqDqfaDRSr74jP4ftbHX+P13IPSTABYThiyxRtkkU0hND1EbDtqO1/rlaIg1BX0AP0tb1grM9zSQfPFDQKhkksW9Z7546Trhao++TimtCZmWuLlznWk2uE8Zgn1YbjUNS3s+s9e71DseYtcFyRbSTB9cZmn3KOibQD8cE5lNDV+CP0f2oMQ0EwwYSLNpywKeF+6IXzxumvTvPXasCDrmNeCeBJZB/BThZQB6cQentxhduhTOKCZEgjSMMIaeDSpBAeUftCyhDeDFJ9gNE/ZcZOgYhknbdWPKooFfHruMzr5Z/f8CVMmXQFoSneUmQnkPJboFeKtwbI8dy6scWqGalb8qq+KYK1b9POX2zvY1cxzNuIAxGCnvRsiJ5Ir1clu4mANmDMcxcDIYuhTeIc1e5hLIQJJkc07U/YwaLplUMKc0q0Ig857+TAE98sR6E3ug7YwaEkv2Q0F1BQGQExjVgNtNzMewhWfr6De3rzV0ZnUdD1XPwW2kt8sUBZYElmb6Wu4cBWq3G6qoCFAbPnI81PLud8CcImrBXbJGtPrRB0=
  app: radiant-dusk-68990
  on:
    repo: ASARIR/projet
