language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  addons:
    code_climate:
        repo_token: f40dcc641a9142b6074dcc91d791c1c67c03f279db2fa9003d00375e41ec4518
  api_key:
    secure: MhXY1ArGPCl6TpzC56hBT19z36p3skDLF7AI4rp0A2JL8wKcmvFGMfjlDk8tr8YQc6hVU8zwlSrt/KEyRclmY3ByhmRp/zbbBhNVexLdV8EwMAyZeYOrvIiCtq+0S+1pFTo46Vm6QsY+bIfVep0Gs3haxnJIsWJBZAqqkVxcHb1r+gUTe7bimWmBKkXXc8aWVbsFp4lnoTIB9EoR2mUJsmpSf8iwng9rLV3bQsCv+UIVhSnyn9Yw2fiahOz99XNa4VLxTFIegVsIXeV072A9MThDywp3wJyLaXFaZ018crdFCYhCAcXQC4SyXeNEDFdERkiV/Vt8FzlShTmT5xxi1csq8eIZLG0ggUuCgeBoVE9rU2MI0vWDLcQyqjHqZouxwnbnxCNebhl88u4TgkE2V/iyjpO4hHWf5ZJYhJx9BV92WsLgtMEWlnmmQ/hO3z5uvoQCwrMsFFJYpcjBmlXXeR7eofGFCT3DhtxJdEC2fJXMpPtV/SQG4X8UXv2M1TaY68nFgp//wKE/urhhyCU+jq0NrxV7Mj1tEyGV+ZOzIpY7qugsraHMo7ENwtwlhMaQPDkrYohBxWbwlHjw1nlRFwN096w3aKOjdVYP0zzX6DZHhfTcIvGr6V4HTBAT2xL/taFpb5hmSvgg/sJs0caQNFxFkYm1MQc14mN4seiMpM4=
  app: limitless-dusk-16472
  on:
    repo: ASARIR/projet
    
    